### ISSUE TITLE
Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/github/hiteshsondhi88/libffmpeg/ArmArchHelper;

### ISSUE THREAD

**Issue by EatedApple** [hiteshsondhi88/ffmpeg-android-java#123]
FATAL EXCEPTION: main
                                                                  Process: com.kamsung.anvang, PID: 9665
                                                                  java.lang.UnsatisfiedLinkError: Couldn't load ARM_ARCH from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xxx.xxxx-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.com.xxx.xxxx-1, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                      at java.lang.System.loadLibrary(System.java:526)
                                                                      at com.github.hiteshsondhi88.libffmpeg.ArmArchHelper.<clinit>(ArmArchHelper.java:5)
                                                                      at com.github.hiteshsondhi88.libffmpeg.CpuArchHelper.getCpuArch(CpuArchHelper.java:14)
                                                                      at com.github.hiteshsondhi88.libffmpeg.FFmpeg.loadBinary(FFmpeg.java:38)
                                                                      at com.kamsung.anvang.control.FFmpegHelper.loadFFMpegBinary(FFmpegHelper.java:30)

**Comment by NilaySheth** [comment]
I am also facing this same issue. Has anyone been able to resolve it?

**Comment by MrUncleYzw** [comment]
@EatedApple Did you solved this problem?

**Comment by astro5206771** [comment]
it also occur on me;Did someone solve it？

**Comment by githubdoramon** [comment]
Getting this in armeabi-v7a... But I guess no one cares for this library anymore
