### ISSUE TITLE
ffmpeg binary file is not found in /files

### ISSUE THREAD

**Issue by dhiraj** [hiteshsondhi88/ffmpeg-android-java#153]
I'm trying to use this awesome library to get ffmpeg integration in my app, but when I attempt to run it I'm getting a No such file or directory error.

I'm using the latest Android Studio (2.2.1), latest gradle (2.2.1) with API target 22.

```
E/FFmpeg: Exception while trying to run: [Ljava.lang.String;@811ecd9
                                                                   java.io.IOException: Error running exec(). Command: [/data/user/0/my.package.name/files/ffmpeg, -v warning -t 5 -i /storage/emulated/0/Movies/350950598.mp4 -vf "fps=10,scale=320:-1:flags=lanczos,palettegen=" -y /storage/emulated/0/Movies/palette.png] Working Directory: null Environment: null
                                                                       at java.lang.ProcessManager.exec(ProcessManager.java:211)
                                                                       at java.lang.Runtime.exec(Runtime.java:174)
                                                                       at java.lang.Runtime.exec(Runtime.java:129)
                                                                       at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
                                                                       at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
                                                                       at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                    Caused by: java.io.IOException: No such file or directory
                                                                       at java.lang.ProcessManager.exec(Native Method)
                                                                       at java.lang.ProcessManager.exec(ProcessManager.java:209)
                                                                       at java.lang.Runtime.exec(Runtime.java:174) 
                                                                       at java.lang.Runtime.exec(Runtime.java:129) 
                                                                       at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10) 
                                                                       at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38) 
                                                                       at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10) 
                                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                       at java.lang.Thread.run(Thread.java:818) 

```

I did an `adb shell` and cd'd to the \files folder within my app directory and then `run-as` to check with `ls`, and the ffmpeg file is actually not present.

What gives, why is the binary not being deployed?

**Comment by dhcn** [comment]
before excute cmd ,first you need call function loadBinary(FFmpegLoadBinaryResponseHandler ffmpegLoadBinaryResponseHandler)

**Comment by dhiraj** [comment]
Yep, I figured out that I had to do this, after I re-read the instructions. Thanks dhcn, I'm closing the issue.

**Comment by imrankhanpatan** [comment]
Thanks dhcn
