### ISSUE TITLE
With environvenmentVars set, execute will cause IO exception

### ISSUE THREAD

**Issue by JunfeiW** [hiteshsondhi88/ffmpeg-android-java#159]
I added a env, which is not harmful to anything, as follows: 
HashMap<String, String> env1 = new HashMap<String, String>();
env1.put("a", "a");

However, when execute command, it will failed with exception:

E/FFmpeg: Exception while trying to run: [Ljava.lang.String;@3e95a0bd
          java.io.IOException: Error running exec(). Command: [a=a /data/data/com.test.abc/files/ffmpeg, -y, -i, /storage/emulated/0/Android/data/com.test.abc/files/video/La leggenda del pianista sull'oceano/57bd5f5a8ac24700631918df.mp4, -i, /storage/emulated/0/Android/data/com.test.abc/files/video/La leggenda del pianista sull'oceano/useraudioswithbackground.aac, -c:v, copy, -c:a, copy, -strict, -experimental, -map, 0:v:0, -map, 1:a:0, -bsf, aac_adtstoasc, /storage/emulated/0/Android/data/com.test.abc/files/video/La leggenda del pianista sull'oceano/57bd5f5a8ac24700631918df_ff.mp4] Working Directory: null Environment: null
              at java.lang.ProcessManager.exec(ProcessManager.java:211)
              at java.lang.Runtime.exec(Runtime.java:173)
              at java.lang.Runtime.exec(Runtime.java:128)
              at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)

**Comment by JunfeiW** [comment]
if without the env, everything works fine

**Comment by JunfeiW** [comment]
Since nobody answered, I did do some homework for this problem.
When env is set, getFFmpeg will be run to :
if (environmentVars != null) {
            for (Map.Entry<String, String> var : environmentVars.entrySet()) {
                ffmpegCommand += var.getKey()+"="+var.getValue()+" ";
            }
        }
        ffmpegCommand += getFFmpeg(context);

Which means, add env at the begin of call command. 
And execute : 
Runtime.getRuntime().exec(commandString)

However, there is a problem, this is not acceptable for android.
Should call this function:
    public Process exec(String[] progArray, String[] envp) throws java.io.IOException {

Which means, should pass the env to here ..

**Comment by JunfeiW** [comment]
Now, please have a try this lib with environments and fix the problem if I'm right.
Great thanks ...

**Comment by JunfeiW** [comment]
Hi, guy, nobody care about this serious problem?

**Comment by JunfeiW** [comment]
So, this project is not maintained anymore？

**Comment by ruha9005** [comment]
@JunfeiW 
> HashMap<String, String> env1 = new HashMap<String, String>();
> env1.put("a", "a");

Explain the "a" string. And try this:
String key = "-i";
String value = videoFile.getAbsolutePath();
HashMap<String, String> env1 = new HashMap<String, String>();
env1.put(key, value);

**Comment by tzutalin** [comment]
@JunfeiW ,
  I met the same problem. Is calling `exec(String[] progArray, String[] envp)` a solution?

**Comment by JunfeiW** [comment]
I think so, but since it is not working, we did change the functionality

**Comment by tzutalin** [comment]
@JunfeiW,
    As you said, it works by changing the method.

**Comment by JunfeiW** [comment]
Great! Nice to hear that.

**Comment by lucazin** [comment]
Hello folks

i try the solution but i get the same error .. 

Error running exec(). Command: [a=a /data/user/0/br.com.oneplace/files/ffmpeg, -y, -i, /storage/emulated/0/OnePlace/Videos/Enviados/OnePlace_Video_TempFile.mp4, -c:v, libx264, -crf, 40, -b:v, 512k, -c:a, aac, /storage/emulated/0/OnePlace/Videos/Enviados/OnePlace_Video__180416_223500.3gp] Working Directory: null Environment: null


i put a hashmap 
HashMap<String, String> env1 = new HashMap<String, String>();
        env1.put("a", "a");

but no works in galaxy s5  android 6.0.1

please help me

**Comment by lucazin** [comment]
i dont know working directory and enviroment
