### ISSUE TITLE
null pointer exception while running    ffmpeg.execute method

### ISSUE THREAD

**Issue by rohan35** [hiteshsondhi88/ffmpeg-android-java#191]
I am getting the below error while running execute method of ffmpeg .On Failure methods gets called with empty message 

E/FFmpeg: Error running FFmpeg
                                                                            java.lang.NullPointerException
                                                                                at java.lang.ProcessBuilder.start(ProcessBuilder.java:952)
                                                                                at java.lang.Runtime.exec(Runtime.java:691)
                                                                                at java.lang.Runtime.exec(Runtime.java:559)
                                                                                at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
                                                                                at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
                                                                                at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                at java.lang.Thread.run(Thread.java:761)

**Comment by zubairehman** [comment]
did u get any solution.?

**Comment by pduthoit** [comment]
Hey @rohan35, did you find the  solution ? I'm actually struggling to find where this error comes from.
Thank you !

**Comment by teganburns** [comment]
My problem was that the 'command' variable in FFmpeg.execute(String command, Handler h) was getting cleaned up before the callback could be triggered.

**Comment by chiragpatel3131** [comment]
hello rohan3 you closed the issue did u get any solution for this im facing the same

**Comment by develoboi** [comment]
hello @rohan35 please share the solution bcoz you have closed issue.
