### ISSUE TITLE
java.io.IOException: Cannot run program "/data/user/0/com.zhou.ffmpegdemo/files/ffmpeg": error=2, No such file or directory

### ISSUE THREAD

**Issue by zhjjoy** [hiteshsondhi88/ffmpeg-android-java#215]
java.io.IOException: Cannot run program "/data/user/0/com.zhou.ffmpegdemo/files/ffmpeg": error=2, No such file or directory
                                                                 at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
                                                                 at java.lang.Runtime.exec(Runtime.java:691)
                                                                 at java.lang.Runtime.exec(Runtime.java:559)
                                                                 at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
                                                                 at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
                                                                 at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:761)
                                                              Caused by: java.io.IOException: error=2, No such file or directory
                                                                 at java.lang.UNIXProcess.forkAndExec(Native Method)
                                                                 at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
                                                                 at java.lang.ProcessImpl.start(ProcessImpl.java:128)
                                                                 at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
                                                                 at java.lang.Runtime.exec(Runtime.java:691) 
                                                                 at java.lang.Runtime.exec(Runtime.java:559) 
                                                                 at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10) 
                                                                 at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38) 
                                                                 at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10) 
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                 at java.lang.Thread.run(Thread.java:761)

**Comment by faith-hb** [comment]
I have this problem, too

**Comment by amintabar** [comment]
I have this problem too

**Comment by doomers** [comment]
same problem here

**Comment by matteinn** [comment]
@zhjjoy @faith-hb @amintabar @doomers please have a look at the "Load binary" paragraph here http://writingminds.github.io/ffmpeg-android-java/

**Comment by channae** [comment]
I'm facing the same issue. Anyone found a solution for this?

**Comment by andrey2ag** [comment]
@channae 
FFmpeg needs to be initiliazed before use it calling
`ffmpeg.loadBinary.....` 
then you will be able to do `ffmpeg.execute(.....`

**Comment by Sp4Rx** [comment]
What is the best place to call **ffmpeg.loadBinary**? Shall I call it in the application class as it is an one time process. @andrey2ag

**Comment by faith-hb** [comment]
> @channae
> FFmpeg needs to be initiliazed before use it calling
> `ffmpeg.loadBinary.....`
> then you will be able to do `ffmpeg.execute(.....`

very nice

**Comment by pratikbutani** [comment]
> What is the best place to call **ffmpeg.loadBinary**? Shall I call it in the application class as it is an one time process. @andrey2ag

Yes, Absolutely.
