### ISSUE TITLE
java.io.IOException: Cannot run program "/data/user/0/sample.user.com.speakerrecognitionsampleapp/files/ffmpeg": error=2, No such file or directory

### ISSUE THREAD

**Issue by channae** [hiteshsondhi88/ffmpeg-android-java#277]
I'm getting following error when trying to call splitAudio.getSplitCommand(uri.getPath(), uri.getPath() + "-split", "00:00:02", "00:00:10");  within onActivityResult. 

Here is how I get the uri, "Uri uri = data.getData();"

Stacktrace

 java.io.IOException: Cannot run program "/data/user/0/sample.user.com.speakerrecognitionsampleapp/files/ffmpeg": error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
                                                                                          at java.lang.Runtime.exec(Runtime.java:691)
                                                                                          at java.lang.Runtime.exec(Runtime.java:559)
                                                                                          at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
                                                                                          at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
                                                                                          at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                          at java.lang.Thread.run(Thread.java:762)
                                                                                       Caused by: java.io.IOException: error=2, No such file or directory
                                                                                          at java.lang.UNIXProcess.forkAndExec(Native Method)
                                                                                          at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
                                                                                          at java.lang.ProcessImpl.start(ProcessImpl.java:128)
                                                                                          at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
                                                                                          at java.lang.Runtime.exec(Runtime.java:691) 
                                                                                          at java.lang.Runtime.exec(Runtime.java:559) 
                                                                                          at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10) 
                                                                                          at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38) 
                                                                                          at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10) 
                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:304) 
                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) stamps": [

**Comment by channae** [comment]
I was able to solve this. It was occurring since I haven't executed following block in my onCreate method.  Calling this would copy corresponding ffmpeg executable file to the device etc which requires for the next stop. 

ffmpeg = FFmpeg.getInstance(context);
        try {
            ffmpeg.loadBinary(new LoadBinaryResponseHandler() {

                @Override
                public void onStart() {
                    Log.d(TAG,"ffmpeg load binary started...");
                }

                @Override
                public void onFailure() {
                    Log.e(TAG,"ffmpeg load binary failure...");
                }

                @Override
                public void onSuccess() {
                    Log.d(TAG,"ffmpeg load binary success...");
                }

                @Override
                public void onFinish() {
                    Log.d(TAG,"ffmpeg load binary finish...");
                }
            });
        } catch (FFmpegNotSupportedException e) {
            // Handle if FFmpeg is not supported by device
        }

**Comment by riimuru** [comment]
> I was able to solve this. It was occurring since I haven't executed following block in my onCreate method. Calling this would copy corresponding ffmpeg executable file to the device etc which requires for the next stop.
> 
> ffmpeg = FFmpeg.getInstance(context);
> try {
> ffmpeg.loadBinary(new LoadBinaryResponseHandler() {
> 
> ```
>             @Override
>             public void onStart() {
>                 Log.d(TAG,"ffmpeg load binary started...");
>             }
> 
>             @Override
>             public void onFailure() {
>                 Log.e(TAG,"ffmpeg load binary failure...");
>             }
> 
>             @Override
>             public void onSuccess() {
>                 Log.d(TAG,"ffmpeg load binary success...");
>             }
> 
>             @Override
>             public void onFinish() {
>                 Log.d(TAG,"ffmpeg load binary finish...");
>             }
>         });
>     } catch (FFmpegNotSupportedException e) {
>         // Handle if FFmpeg is not supported by device
>     }
> ```

what do i have to put on the context variable?
