### ISSUE TITLE
Permission Denied Exception

### ISSUE THREAD

**Issue by digiholicinfotech** [hiteshsondhi88/ffmpeg-android-java#365]
E/FFmpeg: Exception while trying to run: [Ljava.lang.String;@426024e
    java.io.IOException: Cannot run program "/data/user/0/PACKAGE NAME/files/ffmpeg": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:698)
        at java.lang.Runtime.exec(Runtime.java:563)
        at com.github.kohiyadav.libffmpeg.ShellCommand.run(ShellCommand.java:10)
        at com.github.kohiyadav.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
        at com.github.kohiyadav.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:698) 
        at java.lang.Runtime.exec(Runtime.java:563) 
        at com.github.kohiyadav.libffmpeg.ShellCommand.run(ShellCommand.java:10) 
        at com.github.kohiyadav.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38) 
        at com.github.kohiyadav.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by SuryaChundawat** [comment]
getting the same issue

**Comment by ghost** [comment]
WritingMinds ffmpeg-android library is obsolete and outdated. It does not support Android Q. Therefore its recommended to switch to different new ffmpeg library.
Here's one you might find helpful.
[https://github.com/tanersener/mobile-ffmpeg/](url)

**Comment by ghost** [comment]
#361 
A similar issue

**Comment by yxwandroid** [comment]
A similar issue

**Comment by yyms3275** [comment]
> WritingMinds ffmpeg-android library is obsolete and outdated. It does not support Android Q. Therefore its recommended to switch to different new ffmpeg library.
> Here's one you might find helpful.
> [https://github.com/tanersener/mobile-ffmpeg/](url)

Thanks solved the problem.
