### ISSUE TITLE
java.io.IOException: Error running exec() Working Directory: null Environment: null

### ISSUE THREAD

**Issue by mhamzashahid** [hiteshsondhi88/ffmpeg-android-java#97]
here is my code

`

```
loadFFmpeg();
String cmd="ffmpeg -i /storage/emulated/0/media/audio/a.mp3 -i  /storage/emulated/0/recording.3gp -filter_complex \"[0:a][1:a]amerge=inputs=2[aout]\" -map \"[aout]\" " + outputFile;
            executeFFmpeg(cmd.split(" "));
private void loadFFmpeg() {
    FFmpeg ffmpeg = FFmpeg.getInstance(MainActivity.this.getApplicationContext());
    try {
        ffmpeg.loadBinary(new LoadBinaryResponseHandler() {

            @Override
            public void onStart() {}

            @Override
            public void onFailure() {}

            @Override
            public void onSuccess() {}

            @Override
            public void onFinish() {}
        });
    } catch (FFmpegNotSupportedException e) {
        // Handle if FFmpeg is not supported by device
    }
}

private void executeFFmpeg(String[] cmd)
{

    FFmpeg ffmpeg = FFmpeg.getInstance(MainActivity.this.getApplicationContext());
    try {
        // to execute "ffmpeg -version" command you just need to pass "-version"
        ffmpeg.execute(cmd, new ExecuteBinaryResponseHandler() {

            @Override
            public void onStart() {}

            @Override
            public void onProgress(String message) {}

            @Override
            public void onFailure(String message) {}

            @Override
            public void onSuccess(String message) {}

            @Override
            public void onFinish() {
                stop.setEnabled(false);
                play.setEnabled(true);
            }
        });
    } catch (FFmpegCommandAlreadyRunningException e) {
        // Handle if FFmpeg is already running
    }
}`
```

and the error i get is

> 05-12 16:19:16.062 29397-29720/com.flipartstudio.playandrecord E/FFmpeg: Exception while trying to run: [Ljava.lang.String;@4180b508
>                                                                          java.io.IOException: Error running exec(). Command: [/data/data/com.flipartstudio.playandrecord/files/ffmpeg, ffmpeg, -i, /storage/emulated/0/media/audio/a.mp3, -i, /storage/emulated/0/recording.3gp, -filter_complex, "[0:a][1:a]amerge=inputs=2[aout]", -map, "[aout]", /storage/emulated/0/recording.3gp] Working Directory: null Environment: null
>                                                                              at java.lang.ProcessManager.exec(ProcessManager.java:211)
>                                                                              at java.lang.Runtime.exec(Runtime.java:168)
>                                                                              at java.lang.Runtime.exec(Runtime.java:123)
>                                                                              at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
>                                                                              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
>                                                                              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
>                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:287)
>                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234)
>                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
>                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
>                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
>                                                                              at java.lang.Thread.run(Thread.java:856)
>                                                                           Caused by: java.io.IOException: No such file or directory
>                                                                              at java.lang.ProcessManager.exec(Native Method)
>                                                                              at java.lang.ProcessManager.exec(ProcessManager.java:209)
>                                                                              at java.lang.Runtime.exec(Runtime.java:168) 
>                                                                              at java.lang.Runtime.exec(Runtime.java:123) 
>                                                                              at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10) 
>                                                                              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38) 
>                                                                              at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10) 
>                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:287) 
>                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
>                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
>                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
>                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
>                                                                              at java.lang.Thread.run(Thread.java:856) 

I have also added

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

**Comment by waleedsarwar86** [comment]
@mhamzashahid Did you find any fix.I am facing the same issue.

**Comment by moster67** [comment]
Try to remove ffmpeg from your cmd string:
original
`String cmd="ffmpeg -i /storage/emulated/0/media/audio/a.mp3 -i  /storage/emulated/0/recording.3gp -filter_complex \"[0:a][1:a]amerge=inputs=2[aout]\" -map \"[aout]\" " + outputFile;`

modified
`String cmd="-i /storage/emulated/0/media/audio/a.mp3 -i  /storage/emulated/0/recording.3gp -filter_complex \"[0:a][1:a]amerge=inputs=2[aout]\" -map \"[aout]\" " + outputFile;`
